nipkownix/re4_tweaks

- dllmain/dllmain.cpp
Map in 21:9 should exactly match the 16:9 positioning now. Also more accurately match the positioning for merchant item description text.
It bugged me slightly, so I figured I'd fix it myself and save you the trouble :)
> Slightly adjust map icons and merchant item descriptions in ultrawide

- dllmain/dllmain.cpp
- settings/winmm.ini
Tested with 1.1.0 & 1.0.6, hopefully sig should match 1.0.6 JP too.
Might be nice if the INI could also be updated when user moves the window around, via the WndProc hook maybe, though it seems RE4 doesn't always let you move the window for some reason...
(also I still wonder if there's any way to make Windows automatically move it out of the way of taskbar, didn't have any luck with that yet though)
> Add `WindowBorderless`, `WindowPositionX` & `WindowPositionY` settings, fixes #13

- dllmain/dllmain.cpp
- settings/winmm.ini
Added blur fixes from https://github.com/nipkownix/re4_tweaks/issues/5#issuecomment-963766989
Seems to be working across both 1.1.0 & 1.0.6, haven't tried 1.0.6 JP though. Should hopefully match up with the DLL that I posted in that thread, but haven't tried with that many cutscenes yet.
Not sure if there might be a better way to handle the sigs - couldn't sig-scan for the GX funcs themselves since they're all so similar to each other, so had to scan for code that called them instead & find the offset based on the `call` insn, luckily didn't need too much code to handle that though.
I figured `GCBlur` would probably sound better than `DoFBlur` here, but feel free to rename the setting/vars/etc as you like of course!
E: might need to look into increasing the focus-time for …
> Add hooks to make DoF blur closer to GC, add `EnableGCBlur` setting

- dllmain/dllmain.cpp
- settings/winmm.ini
This allows skipping most of the startup logo sequence, it's not entirely skipped as it seems that sequence is needed to load certain things in for the main menu etc, but this method is the best way I've found so far to skip the longer logo sections of it.
Tested with 1.1.0 & 1.0.6, seems to work fine - comes in very useful when you're constantly restarting the game trying to track down an annoying crash :P
> Add `SkipIntroLogos` option to skip the Capcom etc logos at startup

- dllmain/dllmain.cpp
Looks like 1.0.6 debug build works fine with most of the sigs here, only ones that it had trouble with were
```C
// HealthBase pointer
auto pattern = hook::pattern("A1 ? ? ? ?  83 C0 60  6A 10  50  E8");
HealthBase = *pattern.count(1).get(0).get<uint32_t*>(1);
```
and
```C
// Inventory screen mem
pattern = hook::pattern("A1 ? ? ? ? 56 D9 58 ? FF 15 ? ? ? ? 50 FF D7 8B 8D ? ? ? ? 8B 95 ? ? ? ? 89 0D");
ptrpG = injector::ReadMemory<uint32_t*>(pattern.count(1).get(0).get<uint32_t*>(1), true);
```
It turns out both of these actually retrieve the same value too, the pG pointer (0xC06F3C in 1.1.0)
(also my debug menu stuff actually searches for pG yet again as well, so that'd make 3 patterns searching for the same thing 😄)
The pattern I used for debug menu seemed to work across both 1.0.6/1.1.0 …
> Add support for 1.0.6 debug build

- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/WndProcHook.cpp
- dllmain/dllmain.cpp
- dllmain/qtefixes.cpp
- dllmain/tool_menu.cpp
- dllmain/tool_menu_debug.cpp
- settings/settings_string.h
New default for tool menu is now `CTRL+F3`, as not all keyboards have HOME+END, and F1/F2 are used by Imgui things - the combo string will be parsed into a std::vector, which the tool-menu hook iterates over to check if all keys are pressed.
(the combo uses multiple keys to reduce chance of it being pressed by accident, don't want people to get stuck in the tool-menu mode...)
This also changes Setting.cpp so that `key_map` is defined statically (afaik previously it looked like key_map was inited each time KeyMap got called), and changed the `char* type` KeyMap param to a bool instead to get rid of a string compare.
Also added some key name variants to key_map to improve chance of users combo string getting parsed, there were a couple keys that I added to key_map but don't know the DIK of …
> Add `DebugMenuKeyCombination` setting, allows custom tool menu key combo

- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- dllmain/dllmain.cpp
- settings/settings_string.h
This is done with a MakeInline hook (at 0x6F5518 in 1.1.0, sig also works for 1.0.6), so that it can be toggled while in-game fine (hopefully game won't have any issue with this getting switched about...)
I haven't really used MakeInline much before, so there's likely a better way to handle this.
Tested with 1.1.0, 1.0.6 & 1.0.6 debug, would be a good idea to check if JP version still works too though.
If anyone has a better name than `UnlockJPOnly` feel free to post it too!
> `AshleyJPCameraAngles`: unlocks classic camera during Ashley segment

- dllmain/ConsoleWnd.h
- dllmain/LAApatch.cpp
- dllmain/LAApatch.h
- dllmain/WndProcHook.cpp
- dllmain/cfgMenu.cpp
- dllmain/dllmain.cpp
- dllmain/dllmain.h
- dllmain/dllmain.vcxproj
- dllmain/dllmain.vcxproj.filters
As mentioned at #35 
I changed the dialog titles to use 4GB patch instead of LAA patch since people are probably more familar with the 4GB name, added some extra line-breaks in, & also added the `ImGui::SameLine()` fix to the button positions.
Also did a quick test of removing my user permissions from the bio4.exe first before patching - interesting thing is that when I tried running game afterwards, the patch still worked fine! Looks like something added all the permissions back to the EXE after I ran it...
Guessing that's Steam related since game was in SteamApps folder, if I tried with a copy of the game in another folder then removing permissions gave a more expected result (excuse weird font in this pic, for some reason when I run 1.0.6 it scales the window weirdly for some reason) …
> Check if EXE is 4GB patched, prompt user & allow patching if not

- Wrappers/wrapper.def
- Wrappers/wrapper.h
- Wrappers/x3daudio1_7.h
- Wrappers/xinput1_3.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/dllmain.cpp
- dllmain/dllmain.vcxproj
- dllmain/dllmain.vcxproj.filters
- settings/settings_string.h
Both seem to be working with 1.1.0 at least, had to replace the `dsound` ordinals in Wrapper.def since xinput1_3 also requires fixed ordinals in some cases, game doesn't use dsound anyway afaik.
Using xinput1_3 might cause some issues with controllers for some people though, never had issues with it myself, but had some reports about that before (maybe they were using controller mapping software or something like that), x3daudio1_7 should be safer though since there's not much that mess with game audio AFAIK.
E: oh there is https://github.com/kosumosu/x3daudio1_7_hrtf that would conflict with x3daudio1_7 though... unfortunately that also works via the X3DAudio exports like `X3DAudioInitialize` etc, so chainloading with LoadLibrary probably wouldn't help there.
Not sure how much work it'd …
> Wrappers: add `xinput1_3` & `x3daudio1_7` wrappers

- dllmain/dllmain.cpp
Tested with 1.1.0/1.0.6/1.0.6debug, should allow swapping out savegame00.sav for other peoples fine.
Seems the steamID inside the save is also used as part of the CRC calculation, but that should be unaffected, loading from other persons save & making new save seems to rewrite the SteamID part at 0x1E40 with the users one instead.
Fixes #67
> Remove savegame SteamID checks, allows easier save transfers, fixes #67

- dllmain/KeyboardMouseTweaks.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
Seems to work across 1.1.0/1.0.6/1.0.6debug, it might be nice for re4_tweaks to activate this automatically depending on known-bad layouts (or maybe just always activate it, if no other layout besides English shows correctly?)
E: oh I missed the image you posted of all the available keys - I guess that shows that languages besides English must be supported then. Too bad we don't have any list of the ones that work, unless maybe it's all the in-game translations?
E2: updated so that languages that have translation will still be used, and made it enabled by default
Here's a build if anyone is able to test it out:
[re4_tweaks1.7.4-englishKeyFallback.zip](https://github.com/nipkownix/re4_tweaks/files/7991176/re4_tweaks1.7.4-englishKeyFallback.zip)
> FallbackToEnglishKeyIcons: falls back to English key icons for unsupported languages

- dllmain/dllmain.cpp
Broke: letting game filter display modes to only 60Hz ones
Woke: using `EnumDisplaySettings` with NULL device name to get desktop refresh rate
Bespoke: using `EnumDisplayDevices` to get device name of adapter 0 first, to use with `EnumDisplaySettings`
This seemed to fix the green screen issue, I guess EnumDisplaySettings with NULL device was fetching from wrong monitor.
Hopefully `EnumDisplayDevices` device indexes will match up with D3D's, so maybe in future we can use the adapter number from games config.ini with it (right now theres a bunch of places where game ignores adapter number though and hardcodes adapter 0, eg. `D3D_FillDisplayModeVector` - might need to hook the D3D calls they're making, or reimplement the whole caller,  shouldn't be too hard to track them down though since …
> FixDisplayMode: use EnumDisplayDevices to get refresh rate of monitor 0

- dllmain/ConsoleWnd.cpp
- dllmain/ConsoleWnd.h
- dllmain/MouseTurning.cpp
- dllmain/MouseTurning.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/ToolMenu.cpp
- dllmain/ToolMenu.h
- dllmain/WndProcHook.cpp
- dllmain/WndProcHook.h
- dllmain/cfgMenu.cpp
- dllmain/cfgMenu.h
- settings/settings_string.h
From discussion at #83
Using WndProc to get the states would be a lot better, atm there's an issue with bMouseTurnStateChanged where that's only valid for the first `MouseTurnEnabled()` call after state changed, after it's been called once it'll end up resetting the state changed bool at the next call to it (so if that's used more than 1 time in a frame it'd get wrong info), WndProc should let us set that up seperately to all the MouseTurn calls though.
E: oh I missed @RiasatSalminSami's suggestion in that thread:
>-If new mouse controls are enabled: Then the modifier key will switch the mouse controls to default vanilla controls.
>-If new mouse controls are disabled: Then the modifier key will switch the mouse controls to new one.
That's pretty smart actually, so modifier key just …
> MouseTurning: add modifier key-combo to temporarily disable turning

- .github/workflows/ci.yml
Thanks for all the hard work! I'm not familiar with C++ and reverse engineering, so I tried to find another way to contribute.
This adds a GitHub Actions workflow to automatically build the project (with both `Debug` and `Release` configurations) and upload both DLL outputs as an artifact. Might be useful to let other people test new commits and PRs, while also ensuring reproducible builds of the project.
I don't know if this setup is sufficient, though. I might be missing some options to `msbuild`.
We can also automate the release with something like [action-gh-release](https://github.com/softprops/action-gh-release), but I suppose you probably want to do it manually so you can test things out ~~(and add the `.ini` as it seems to be written manually?)~~
The result is something like this …
> Add GitHub Actions workflow to build the project

- .github/workflows/ci.yml
This should fix the build. Context: https://github.com/nipkownix/re4_tweaks/pull/102#issuecomment-1035674261
> Use `windows-2022` build image on GitHub Actions

- dllmain/dllmain.cpp
Includes the patch mentioned at https://github.com/nipkownix/re4_tweaks/issues/22#issuecomment-980542000, patching both `cPlLeon::initCloth` & `cPlLeon::moveCloth` (thanks to @RiasatSalminSami for reminding us about it!)
I still think it's weird they included code to check for this costume specifically though, doesn't seem that accidental to me - but since the patch mostly seems to work fine I guess we should be good, if anyone does find a problem with it we can probably just add a check for whatever edge-case has issues with it instead.
If anyone wants to test this, a build with this + RaiseInventoryAlloc fixes is at https://github.com/nipkownix/re4_tweaks/files/8055010/dinput8-tacticalVestPhysics.zip
As noted at https://github.com/nipkownix/re4_tweaks/issues/22#issuecomment-1037799043 …
> Add patch to allow physics on tactical vest

- dllmain/HandleLimits.cpp
- dllmain/ToolMenuLights.cpp
Seems to solve the invisible items bug, many thanks to qingsheng8848 for posting code for their fix! (and also to everyone that helped debug it with us too!)
Cleaned up code a little, removed pointers/hooks that are no longer needed etc.
Should probably spend some time testing game with these changes to make sure heap increases don't break anything else, if anyone wants to help try them there's a build available here: [dinput8-heapHacks-noConsole-clean.zip](https://github.com/nipkownix/re4_tweaks/files/8035322/dinput8-heapHacks-noConsole-clean.zip)
> RaiseInventoryAlloc: increase game heap sizes instead of pointing to our own buffers, fixes #58

- dllmain/60fpsFixes.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
As explained at https://github.com/nipkownix/re4_tweaks/issues/22#issuecomment-1042438416 there's two functions related to Ashley bust physics, one for player-controlled Ashley & one for follower Ashley, on GC these two funcs are pretty much identical, but on PC it seems they updated the `cSubChar` version to make use of delta-time to fix physics speed at different framerates, but didn't copy that fix over to the `cPlAshley` function for some reason.
This hook pretty much just recreates that delta-time code inside `cPlAshley`, making physics apply at same rate despite framerate being used.
In effect this seems to slow down the physics at 60FPS - making it match the 30FPS physics speed - though I'm not sure if this helps with the main issue people had with 60FPS Ashley physics (maybe …
> FixAshleyBustPhysics: fixes framerate difference on physics applied to Ashley

- dllmain/60fpsFixes.cpp
- dllmain/ToolMenuLights.cpp
- dllmain/dllmain.cpp
Fixes #127
I'm sure there were more uses of pG around though (which is why I thought it was fine to use that ptrpG originally), but haven't found them yet, maybe they got removed during RaiseInventoryAlloc fixes or something.
> ptrpG: move to dllmain.cpp, make uint8_t**

- dllmain/60fpsFixes.cpp
- dllmain/ExceptionHandler.cpp
- dllmain/Game.cpp
- dllmain/Game.h
- dllmain/ToolMenu.cpp
- dllmain/ToolMenuLights.cpp
- dllmain/dllmain.cpp
- dllmain/dllmain.h
- dllmain/dllmain.vcxproj
- dllmain/dllmain.vcxproj.filters
Moved some of the more common pointers & game-related structs to a Game.h header, and made them accessible through getter-only `GlobalPtr()` `PlayerPtr()` etc funcs.
Also added structs like `GLOBALS` etc from my IDB here, so we can access the fields normally instead of needing to use ugly pointer offsets, these structs are really barebones atm, but lets us get rid of most of those pointer accesses at least.
(just hope those structs all match between different game versions, seems like most things get stored at the same offset at least, so don't think they'd differ _too_ much)
If you think anything else should be moved there too let me know, wasn't really sure how much to put in there.
> Game.h: move common Game pointers/structs to single header

- dllmain/ToolMenu.cpp
- dllmain/ToolMenuDebug.cpp
- dllmain/dllmain.cpp
- dllmain/dllmain.h
Seems to be working across all 3 versions now.
I noticed 1.0.6debug would crash if `EnableDebugMenu` was set to true though - looks like I forgot to update some things to use `GameVersionIsDebug()` instead, oops..
With those updated it should work fine now.
> SilenceArmoredAshley: fix for pattern not matching 1.1.0 properly, fixes #131

- dllmain/KeyboardMouseTweaks.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
Allows sprint to stay toggled until the FORWARD key is released, the toggle can be enabled/disabled during runtime at will.
It might be nice if this could be extended so that pressing sprint key again could untoggle it, but guess that might need some extra code to track when KEY_RUN was released & then pressed again (or maybe not, maybe `Key.buttonsTriggered_20` / `Key.buttonsReleased_28` could be made use of instead, not sure)
I think this might also affect controller too but haven't tried it myself, if it works fine there I guess maybe should move it to a different category instead.
Thanks to nipkownix for actually getting the hook to work too, seems I need to brush up on ASM some more...
Tested with 1.1.0/1.0.6/1.0.6debug, seems to work fine across them all.
(btw if anyone used the hex …
> UseSprintToggle: allows toggling sprint instead of needing to hold it, fixes #130

- dllmain/60fpsFixes.cpp
- dllmain/LoggingInit.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
This is mostly useful with high framerates (where backward turning happens almost instantly), but it does slightly improve 60FPS too, making it match up with the 30FPS speed - also seems like the camera angle when turning gets improved by it a little bit as well.
(kinda silly that they didn't include this themselves, they did update pl_R1_Walk/pl_R1_Run to make use of deltaTime, but didn't bother with anything else...)
This also patches `pl_R1_KlauserAttack` since that also made use of the same `cPlayer::SPEED_WALK_TURN` var, but not really sure how to test that out yet, if anyone can try it out would appreciate it!
Tested with 1.1.0/1.0.6/1.0.6dbg, you can see the difference pretty easily by toggling it in cfgMenu while turning backwards.
> FixTurningSpeed: makes backwards turn speed consistent between framerates

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Adds the templates from https://github.com/emoose/re4_tweaks/issues/new/choose
I think merging it should be enough for github to pick it up, but if not you might need to go into Settings page -> scroll down to Issues section -> `Set up templates`, and see if something has to be enabled there.
Of course feel free to edit the branch if you want to change anything.
> Add issue templates for bugs & features

- dllmain/Game.h
- dllmain/Misc.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
Some builds like JP/GER have low-violence-only EXEs, this should allow those to have full violence enabled instead, similarly full-violence EXEs should now be able to act like low-violence ones too.
More details in #153
Tested across 1.0.6/1.0.6jpn/1.0.6dbg/1.1.0, seems to be updating the pSys->field_9 field fine, haven't been able to test with German release yet though since I don't have the EXE for it atm.
I'm not totally sure if all the violence censorship is removed in JP/GER however since I'm not that familiar with those versions.
**If someone with those versions wants to try testing**, here's a build of this PR with violence set to full: [re4_tweaks-violenceLevelOverride.zip](https://github.com/nipkownix/re4_tweaks/files/8330405/re4_tweaks-violenceLevelOverride.zip)
E: ah, I've been …
> ViolenceLevelOverride: allows overriding level of violence in the game

- dllmain/KeyboardMouseTweaks.cpp
- dllmain/LoggingInit.cpp
- dllmain/Patches.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
Hey hope all is well, here's a PR for the jet-ski patches mentioned in https://github.com/nipkownix/re4_tweaks/issues/158#issuecomment-1088311559
This just hooks `pl0e_R1_Jump` so we can check for a keyboard/mouse combo before the controller checks, the way I patch around the checks here is a little hacky, as they check for both RT & LT with two seperate test/jz instructions, seemed easier to make the hook return past those tests & skip them if combo pressed instead of needing to hook them both individually, maybe there's a better way to handle that though.
Tested with 1.1.0/1.0.6/1.0.6dbg so far, not sure about other releases, as long as those RT/LT tests are always 0x28 bytes it should be fine, hopefully none of the other versions changed that at all.
Here's a build of these commits, …
> JetSkiTricks: patch gamepad-only code to allow mouse/keyboard combos

- dllmain/LoggingInit.cpp
- dllmain/Misc.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
This fixes #163, allowing player to bring back the Ashley suplex glitch, thanks to @linkthehylian for suggesting it & helping test changes too!
Video: https://twitter.com/linkthehyIian/status/1514764457578180643
Method: https://github.com/nipkownix/re4_tweaks/issues/163#issuecomment-1099741577
I was hoping that the patch could also act as a fix to allow Ashley to Kick instead (the way they added the Ashley-check to the suplex func meant Ashley wouldn't have any action at all for downed enemies...), but right now it seems this fix doesn't actually work for that... but at least this lets us control it at runtime though.
Maybe looking into `em10ActEvtSetKick` some more could let us get Kick working, seems to have a bunch of player-type checks inside it at least, I guess something there must …
> AllowAshleySuplex: allows Ashley to suplex in very specific situations

- dllmain/Settings.cpp
Small thing I noticed, seems OverrideCostumes setting is read from INI, but never got written back, don't think that was intentional, so here's a quick fix 😸
> OverrideCostumes: write setting value to INI

- dist/Bin32/re4_tweaks/setting_overrides/overrides_info.txt
- dllmain/DisplayTweaks.cpp
- dllmain/LoggingInit.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- dllmain/dllmain.vcxproj
- settings/settings_string.h
Another PR for you :p mainly to make sure the new VolumeBGM/SE/etc settings work with override files too. (should have added this in the PR for it earlier, ah well)
To sweeten up this PR I also found a way to speedup debug startup time by a ton, just set some files that we aren't likely to try debugging/stepping-thru to use full optimization, now instead of needing to wait 10+ seconds after starting debug, game should start almost instantly when running under debugger, and AFAIK it shouldn't affect us trying to breakpoint any of our code :)
(E: changed it to only affect Patterns.cpp instead, seems that's the main file that affected startup speed)
E: also found a nice build-time speedup as well, release rebuild went from 30 seconds to ~6 for me now, nice 🐱
> AudioTweaks: fixup settings for INI overrides, & speedup build/startup

- dllmain/dllmain.vcxproj
Really wish I'd thought of this sooner, don't currently have an E:\ drive on this PC so I've had to edit the project settings every time I've cloned the repo :p, with this we should be able to have it use our own paths automatically instead.
The env var can be added pretty easily, https://thegeekpage.com/environment-variables-in-windows-11/ mentions a pretty simple way (on Win11 you can pretty much just type "Env" into start menu and it should find it for you)
It'd be nice if we could fill the Debugging settings to point at bio4.exe automatically as well, but think that isn't saved in .vcxproj...
E: oh seems debugging stuff can be copied from the .user file into .vcxproj, sweet, added it below. (wouldn't work with % for some reason but luckily $ worked)
> vcxproj: use %BIO4_BIN% environment variable as DLL dest path

- dllmain/Game.h
- dllmain/LoggingInit.cpp
- dllmain/Misc.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
As requested in #213 
Don't know whether you want to add this or not, think it might be useful for mod makers since they might not want players to speedrun through their mod (so they could use a settings override file to try forcing this enabled)
Besides that I'm not really sure if it has that much use, tho maybe there's some players that would like to force themselves to play without glitches too, guess this could maybe help to ensure that.
Should work on all the usual EXEs.
E: hm, probably should have documented what actually caused the glitch too...
E2: done
> FixDitmanGlitch: fixes the ditman speedup glitch

- dllmain/KeyboardMouseTweaks.cpp
Small thing I noticed while testing #257, though even without that you can notice a difference between aim sensitivity at 30 vs 60, this seems to help make them more consistent.
Not sure if the non-rawinput `(ptrMouseDeltaX) = (int32_t)regs.eax;` path might also need deltatime applied too.. will try checking that soon.
E: seems like it might, will update PR in a sec.
~~E2: hmm, can't seem to adjust non-rawinput with the same method, dividing by deltaTime makes aiming go all over the place, even when deltaTime is 1? weird.~~
~~If anyone has any ideas please let me know, otherwise I guess this fix is just for rawinput atm...~~
E3: ah nvm, regs.eax was uint but needed to be int, seems to work fine now, pushed with new fix.
> MouseDelta: apply deltaTime, makes aim speed consistent across framerates

- .github/ISSUE_TEMPLATE/bug_report.yaml
Included a link to the BIO4.sfv that came with 1.1, since I'm not sure whether that SFV is included in the update-only release.
E: ugh it got made as a draft PR again, should be fixed I think
> bug_report.yaml: update links for HDProject 1.1

- dllmain/EndSceneHook.cpp
- dllmain/LAApatch.cpp
- dllmain/Misc.cpp
- dllmain/Patches.h
- dllmain/WndProcHook.cpp
Changed it to use standard `MessageBox` before game window is shown or any textures are loaded.
Had to move the actual call to our LAA check stuff to our `CreateWindow` hook instead, tried handling it inside `DllMain` but that just made `ShellExecute` hang instead of relaunching, AFAIK that's something to do with [loader lock issues](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices)...
Seems to patch/relaunch it fine this way though, also tested with EXE renamed after launching to make sure error msg func still works, all seems OK.
Since the game window doesn't even have a chance to show before this I removed part of the text about needing to relaunch the game, could maybe even remove the messagebox after the patch has finished and just go straight …
> LAApatch: prompt user before game window is created or any textures loaded

- dllmain/AspectRatioTweaks.cpp
- dllmain/Game.cpp
- dllmain/Game.h
- dllmain/ModExpansion.cpp
- dllmain/Patches.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- dllmain/dllmain.cpp
- dllmain/dllmain.vcxproj
- dllmain/dllmain.vcxproj.filters
- settings/settings_string.h
Separated the ESL expansion stuff from #266, since I'm probably gonna redo that PR eventually, and I guess it's better to get this stuff in sooner than later.
This adds a `EnableModExpansion` setting which enables the hooks for allowing scale/speed to be set inside ESL, had to change how the flag for enabling speed/scale is set though, since it seems 0xA might actually be in use (I didn't see any code using it, but the field is defined)
Now instead of setting 0xA to 1, you'll need to set the first nibble of it to F instead.
eg. if 0xA was set to `03`, you'd set it to `F3`, or if 0xA is `00` just set it to `F0`.
With that set the last 4 bytes of the ESL entry will be treated as two uint16_t percentage values, first one as speed percent, second as scale percent.
Also added stuff to allow …
> EnableModExpansion: allows overriding scale/speed inside ESL entries

- dllmain/DisplayTweaks.cpp
- dllmain/Game.cpp
- dllmain/Game.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings_string.h
As discussed at https://github.com/nipkownix/re4_tweaks/issues/44#issuecomment-1178293241, this implements the `FPS_ACCURATE` framelimiter from https://github.com/ThirteenAG/d3d9-wrapper/blob/c1480b0c1b40e0ba7b55b8660bd67f911a967421/source/dllmain.cpp#L46
For me this gave a pretty nice CPU usage reduction:
>CPU usage on main menu went from 7% to 1%, ingame from 10% to 4%
[qingsheng8848](https://github.com/nipkownix/re4_tweaks/issues/44#issuecomment-1179459205) also mentioned:
>it works very well, my CPU usage is reduced from 40% to about 20%.
The code is pretty close to the old framelimiter really, but I think the Sleep(1) call helps reduce CPU usage of the busy loop, there's also no longer a 0.01666666... minimum frametime with this so variableframerate above 60 should work better …
> ReplaceFramelimiter: implements new reduced-CPU-usage limiter

- dllmain/Misc.cpp
This fixes the issue with r315 cabinet door being positioned wrong after reloading the stage, thanks to albert for reporting this!
Since it's a very minor fix I figured there's no point adding an option for it, hopefully not much chance of anyone using EXE mods around that code neither, of course I've been wrong about that before though :P
Works across all the usual EXE versions etc.
> Fix r315 cabinet door position issue

- dllmain/ModExpansion.cpp
- dllmain/SDK/em_set.h
This changes the byte we use to indicate that speed/scale should be updated, normally it'd update 0xA, but that field was already defined for use by the game (haven't seen any code that uses it though...), and also seems some stack-allocated `EM_LIST` instances could have random data there too.;
Instead of using that, it looks like the be_flag field has 3 bits unused (0x10/0x20/0x40) that we can appropriate instead, none of the UHD ESL files make use of them at least, and also couldn't find any code that use them neither.
So now to change speed/scale of Em, just add 0x40 to the first byte of the ESL entry (can usually just set first digit to 4)
With the flag moved that gives us 2 extra bits we can use to add further expansions (eg. the disable-laser-interaction flag suggested by …
> ModExpansion: change flag offset 0xA to 0x0 - add 0x40 to set it

- dllmain/DisplayTweaks.cpp
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings.ini
As mentioned at #44, this removes `D3DCREATE_MULTITHREADED` safety flag for a slight FPS improvement, and adds some fixes for deadlocks caused by flag being removed.
A `MultithreadFix` option is added to [DISPLAY] section of INI to toggle it, haven't added GUI stuff for the setting yet though.
This seems to boost FPS by +40-60 for me when running with framelimiter removed, so hopefully will help with FPS drops when playing normally too.
Haven't tested it that much yet though, would appreciate anyone giving it a try! If you get any crashes/hangs please let me know. (maybe create a `CrashDumps` folder next to bio4.exe first before testing it)
You can grab release build from https://github.com/nipkownix/re4_tweaks/suites/7489522135/artifacts/307461430 - just make sure to edit dinput8.ini and …
> MultithreadFix: slight FPS boost via multithread improvements

- dllmain/Misc.cpp
From the comments:
>HACK: Fix for Saddler item drop appearing before cutscene begins, making the item glow show up through the cutscene
>Item gets spawned by em31_R1_Die_Normal when r_no_2 == 4
>Some reason r_no_2 gets set to 4 twice, once immediately after death anim, before the cutscene starts (causing the early item spawn)
>And then later R332RocketShootEnd calls into cEm31::setDieCancel, which forces r_no_2 to 4 (seems to be part of the cutscene code)
>We can patch out the first one by removing the r_no_2 increment call inside the r_no_2 == 3 block, which stops it from spawning early
>However GC (which doesn't have this issue) still seems to have the increment code, so this likely isn't fixing the root cause, but it's a workaround at least...
>Main issue could be the MotionMove check …
> Misc: add workaround fix for Saddler cutscene item glow issue

- dllmain/Game.cpp
- dllmain/Misc.cpp
- dllmain/SDK/objWep.h
- dllmain/SDK/pad.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- settings/settings.ini
https://github.com/nipkownix/re4_tweaks/issues/249
I saw this suggestion and thought it was a good idea. This makes the Matilda feel a lot better when using type II/III config controls, as it's much harder to consistently control the rate of fire when using analog triggers. I suspect that's why RE4VR made this change as well.
(My dream would be if we could one day break the Matilda and its stock up into two items, so we could configure it RE2-style with semi-auto and burst modes)
~On second thought, maybe this option should just be something that forces `joyFireOn` to return false for every weapon, to be consistent. Let me know what you guys think.~
Edit: Hmm, I tried adding a universal semi-auto trigger for the other weapons, and it just doesn't feel good whenever you pull the trigger …
> Added LimitMatildaBurst option

- dllmain/Trainer.cpp
This improves the "Disable Enemy Targeting" trainer patch by adding some extra hooks for some AI funcs.
Two things are changed here, first I noticed `l_pl_378` was used in Em09 to check distance from player & decide whether to melee/walk/etc based on it, so added something to set that to a high number, seemed to help with a couple more enemies but most were still able to track player fine.
Some other Ems use `RouteCkToPos` & `RouteCkPosToPos` to check if it can pathfind to the player though, for those it seems we can just return false and that stops them from tracking properly.
(there were a couple other non-Em things that used those Route funcs too, but seemed like those could be detected & handled fine)
Need to test this out some more though, the few Ems I checked seemed to stop …
> Trainer: improve "Disable Enemy Targeting" patch

- dllmain/Misc.cpp
- dllmain/TitleMenu.cpp
Woops, just noticed that I needed to move this out of the NTSC mode block as well, otherwise trying to skip the difficulty menu in Japanese does nothing.
> OverrideDifficulty: support skipping the difficulty menu when playing in Japanese

- dllmain/Game.cpp
- dllmain/Gameplay.cpp
- dllmain/SDK/pad.h
- dllmain/SDK/player.h
Small problem with the old Matilda burst limit code was that if you pressed fire too early after a reload, nothing would happen. This fixes that.
> Improved LimitMatildaBurst

- dllmain/Game.cpp
- dllmain/Game.h
- dllmain/Gameplay.cpp
- dllmain/Misc.cpp
- dllmain/SDK/item.h
- dllmain/SDK/message.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/cfgMenu.cpp
- dllmain/dllmain.vcxproj
- dllmain/dllmain.vcxproj.filters
- settings/settings.ini
https://github.com/nipkownix/re4_tweaks/issues/434
Workaround fix for [the silencer wrongly suggesting it gives the handgun a 5x crit chance](https://user-images.githubusercontent.com/116680301/211691071-2256ad09-a251-4f76-bc44-200203837815.jpg) when the handgun has less than max firepower:
While we're here, remove the infinite bullets description from the unupgraded Chicago Typewriter:
> Misc: fix some item descriptions in the merchant and examine subscreens

- dllmain/D3D9hook.cpp
- dllmain/DisplayModeFix.cpp
- dllmain/DisplayTweaks.cpp
- dllmain/Game.cpp
- dllmain/Game.h
- dllmain/Misc.cpp
- dllmain/Patches.h
- dllmain/Settings.cpp
- dllmain/Settings.h
- dllmain/WndProcHook.cpp
- dllmain/cfgMenu.cpp
- dllmain/dllmain.vcxproj
- dllmain/dllmain.vcxproj.filters
- dxvk/src/d3d9/d3d9_adapter.cpp
- settings/settings.ini
This should improve the situation in #411.
``FixDisplayMode`` currently works fine, but I was thinking we could still improve it a bit, so this is what I came up with:
- Get rid of the ``CustomRefreshRate`` int. Read the refresh rate from the game's ``config.ini`` instead.
- Provide the option to choose the refresh rate using the game's config menu. To do this, we replace ``D3D_FillDisplayModeVector`` with our own function to make the vector of resolutions. This lets us have a finer control of the list, allowing us to have duplicated resolutions with different refresh rates:
- Hook ``D3D_GetDisplayModeForWidthHeight`` to make it get the display mode with the refresh rate we want, instead of only being able to get 60 Hz refresh rates.
- At startup, validate the display mode in the game's …
> Rewrite FixDisplayMode

- dllmain/AutoUpdater.cpp
- dllmain/CommandLine.cpp
- dllmain/Game.cpp
- dllmain/Patches.h
- dllmain/QTEFixes.cpp
- dllmain/Settings.cpp
- dllmain/UI_Utility.cpp
- dllmain/UI_Utility.h
- dllmain/input.cpp
- includes/iniReader.h
Fixes some minor issues flagged by static analyser, hopefully all the fixes here should be good, but let me know if anything seems wrong.
There were two other things it flagged that I'm not sure about atm, again just minor things though:
Two Em names are defined for 0x13 in Game.cpp:
https://github.com/nipkownix/re4_tweaks/blob/2ff10dd01a5ee460d979826f0b8cb6f68db078a6/dllmain/Game.cpp#L179-L183
There's also no name for Em10 defined there, maybe 0x11 was meant to be 0x10, 0x12 was meant to be 0x11, and first 0x13 was meant to be 0x12? I don't really know what the names of each enemy is though so no idea if that's the case 😅 
and there's a weird check in QTEFixes.cpp of `!var || var`, so it passes every time, is something meant to be checked there? …
> Misc minor fixes from static analyser

- dllmain/ConsoleWnd.cpp
Figured it'd be useful to always log any of the bad OSPanic etc messages (except for OSReport) into log file, might come in handy for crash reports (eg. @linkthehylian's crashing issues at #431 which are maybe mem related, can maybe help track down what fails)
Seems we didn't actually write these logs into our log file though, just console window, added some code to add to log too ~~but haven't been able to test it yet (not really sure how to make game cause an error to try it...)~~
(E: tried out patching part of game to always call OSPanic (nop 94855D) and seemed to log it fine, game did eventually crash after it spammed OSPanic a ton of times though, something in `ImFont::CalcTextSizeA+0x117 in DINPUT8.dll`)
Looks like it should be fine to me though, but let me know if you spot some …
> ConsoleWnd: write game log msgs into log file, always log error msgs

- dllmain/KeyboardMouseTweaks.cpp
This option kept crashing<sup>[[log](https://github.com/nipkownix/re4_tweaks/files/11007378/crash.log)]</sup> for me whenever I'd press escape to skip the Hunnigan cutscene at the start of R101. Added a null check and the crashes stopped.
> FixRetryLoadMouseSelector: crash fix

- dllmain/ControllerTweaks.cpp
- dllmain/Gameplay.cpp
- dllmain/cfgMenu.cpp
- settings/settings.ini
Small update for SmoothAnalogTurning after playtesting back and forth with RE5 some more, realized I needed to up the max turn speed so there's a smoother gradient to the standing left/right turn speed. Feels a lot better now.
Also, minor thing, but I wanted to make the starting difficulty modifiers from NTSC mode independent of restart just in case someone doesn't realize the option requires that when they first configure re4_tweaks and start a new game.
> Tweaked SmoothAnalogTurning
